Bookstore/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Bookstore.Models
{
    public partial class Book
    {
        [Key]
        [Required]
        public int BookId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Author { get; set; }

        [Required]
        public string Publisher { get; set; }

        [Required]
        public string Isbn { get; set; }

        [Required]
        public string Classification { get; set; }

        [Required]
        public string Category { get; set; }

        [Required]
        public int PageCount { get; set; }

        [Required]
        public double Price { get; set; }
    }
}

Bookstore/Models/BookstoreContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Bookstore.Models
{
    public partial class BookstoreContext : DbContext
    {
        public BookstoreContext()
        {
        }

        public BookstoreContext(DbContextOptions<BookstoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Book> Books { get; set; }
    }
}

Bookstore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Bookstore.Models
{
    public class Cart
    {
        public List<CartLineItem> Items { get; set; } = new List<CartLineItem>();

        public void AddItem (Book book, int qty)
        {
            CartLineItem line = Items
                .Where(b => b.Book.BookId == book.BookId)
                .FirstOrDefault();

            if (line == null)
            {
                Items.Add(new CartLineItem
                {
                    Book = book,
                    Quantity = qty
                });
            }
            else
            {
                line.Quantity += qty;
            }
        }

        public double CalculateTotal()
        {
            double sum = Items.Sum(x => x.Quantity * x.Book.Price);
            return sum;
        }
    }

    public class CartLineItem
    {
        public int LineID { get; set; }

        public Book Book { get; set; }

        public int Quantity { get; set; }
    }
}

Bookstore/Models/EFBookstoreRepository.cs
using System;
using System.Linq;

namespace Bookstore.Models
{
    public class EFBookstoreRepository : IBookstoreRepository
    {
        private BookstoreContext context { get; set; }

        public EFBookstoreRepository (BookstoreContext temp)
        {
            context = temp;
        }

        public IQueryable<Book> Books => context.Books;
    }
}

Bookstore/Models/IBookstoreRepository.cs
using System;
using System.Linq;

namespace Bookstore.Models
{
    public interface IBookstoreRepository
    {
        IQueryable<Book> Books { get; }
    }
}

Bookstore/Models/ViewModels/BooksViewModel.cs
using System;
using System.Linq;

namespace Bookstore.Models.ViewModels
{
    public class BooksViewModel
    {
        public IQueryable<Book> Books { get; set; }

        public PageInfo PageInfo { get; set; }
    }
}

Bookstore/Models/ViewModels/PageInfo.cs
using System;

namespace Bookstore.Models.ViewModels
{
    public class PageInfo
    {
        public int TotalNumBooks { get; set; }

        public int BooksPerPage { get; set; }

        public int CurrentPage { get; set; }

        //Figure out how many pages we need
        public int TotalPages => (int)Math.Ceiling((double)TotalNumBooks / BooksPerPage);
    }
}

Bookstore/Components/TypesViewComponent.cs
using System;
using System.Linq;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["Category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Bookstore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bookstore.Models;
using Bookstore.Models.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Bookstore.Controllers
{
    public class HomeController : Controller
    {
        private IBookstoreRepository repo;

        public HomeController (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IActionResult Index(string Category, int pageNum = 1)
        {
            int pageSize = 10;

            var x = new BooksViewModel
            {
                Books = repo.Books
                .Where(b => b.Category == Category || Category == null)
                .OrderBy(b => b.Title)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBooks = (Category == null ? repo.Books.Count() : repo.Books.Where(x => x.Category == Category).Count()),
                    BooksPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };

            return View(x);
        }
    }
}

Bookstore/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Bookstore.Infrastructure;

namespace Bookstore.Pages
{
    public class CartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public CartModel (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public Cart cart { get; set; }

        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            cart.AddItem(b, 1);

            HttpContext.Session.SetJson("cart", cart);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Bookstore/Pages/Cart.cshtml
@page
@model Bookstore.Pages.CartModel
@{
}

<h2>Cart</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.cart.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>$@i.Book.Price</td>
                <td>$@(i.Quantity * i.Book.Price)</td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-info" href="@Model.ReturnUrl">Continue Shopping</a>
</div>

Bookstore/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Bookstore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

@model BooksViewModel

@foreach (Book b in Model.Books)
{
    <partial name="BookSummary" model="b" />
}

<div page-model="@Model.PageInfo" page-action="Index" page-class="btn" page-class-normal="btn-outline-info" page-class-selected="btn-info"
     page-classes-enabled="true" class="btn-group pull-right m-1"></div>

Bookstore/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h3>@Model.Title</h3>
        <span><span style="color:gray;">by</span> @Model.Author</span>

        <span class="badge bg-success" style="float:right; color:white;">
            ISBN @Model.Isbn
        </span>
    </div>

    <ul>
        <li>Publisher: @Model.Publisher</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>@Model.PageCount Pages</li>
        <li>Price: $@Model.Price</li>
    </ul>

    <form method="post" asp-page="/Cart">
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-outline-info float-right">Add to Cart</button>
        </span>
    </form>
</div>

Bookstore/Views/Shared/Components/Types/Default.cshtml
@{
}

@model IEnumerable<string>

<a asp-controller="Home" asp-action="Index" asp-route-Category="" asp-route-pageNum="1" class="btn btn-block btn-outline-secondary">Home</a>

@foreach (string t in Model)
{
    <a asp-controller="Home" asp-action="Index" asp-route-pageNum="1" asp-route-Category="@t"
       class="btn btn-block @(ViewBag.SelectedType == t ? "btn-info" : "btn-outline-secondary")">@t</a>
}

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/MyStyle.css" />
</head>
<body>
    <div class="bg-info text-white p-2">
        <span class="navbar-brand m-lg-2">BookStore</span>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>